# Generated by Django 5.1.2 on 2024-11-13 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Vendor',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
