# Generated by Django 5.1.2 on 2024-12-09 18:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_vendor_date_alter_product_vendor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Vendor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='core.vendor'),
        ),
    ]
