# Generated by Django 5.1.2 on 2024-12-10 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_vendor_product_vendor_vendor_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default='2.99', max_digits=10),
        ),
        migrations.AddField(
            model_name='vendor',
            name='price',
            field=models.DecimalField(decimal_places=2, default='1.99', max_digits=10),
        ),
    ]
