# Generated by Django 5.1.2 on 2024-12-11 06:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_alter_productimages_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.CharField(default='White', max_length=50),
        ),
    ]
