# Generated by Django 5.1.2 on 2024-12-11 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_product_life'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='shipping',
            field=models.CharField(default='Free Shipping', max_length=100),
        ),
    ]
