# Generated by Django 5.1.2 on 2024-12-12 04:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_tags_slug_alter_tags_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tags',
            name='name',
        ),
        migrations.RemoveField(
            model_name='tags',
            name='slug',
        ),
    ]
