# Generated by Django 5.1.2 on 2024-12-23 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_alter_productreview_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='payment_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('Esewa', 'Esewa'), ('Khalti', 'Khalti')], default='COD', max_length=30),
        ),
    ]
