# Generated by Django 5.1.2 on 2024-12-24 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_cartorder_payment_completed_cartorder_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorderitems',
            name='invoice_no',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
