# Generated by Django 5.1.2 on 2024-12-25 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_cartorderitems_invoice_no'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartorderitems',
            name='image',
            field=models.CharField(max_length=200),
        ),
    ]
