# Generated by Django 5.1.2 on 2024-12-25 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_alter_cartorderitems_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='mobile',
            field=models.TextField(default=12345, max_length=10),
            preserve_default=False,
        ),
    ]
