# Generated by Django 5.1.2 on 2025-01-02 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_product_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='sold_quantity',
            field=models.IntegerField(default=0),
        ),
    ]
