# Generated by Django 5.1.2 on 2025-01-02 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_product_sold_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='in_stock',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
