# Generated by Django 5.1.2 on 2025-01-09 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_product_updated_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('ADDED', 'Added'), ('CHANGED', 'Changed'), ('DELETED', 'Deleted')], max_length=50),
        ),
    ]
