# Generated by Django 5.1.2 on 2025-01-09 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_alter_useraction_action_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraction',
            name='action_type',
            field=models.CharField(choices=[('LOGIN', 'Login'), ('LOGOUT', 'Logout'), ('PRODUCT_CREATED', 'Product Created'), ('PRODUCT_UPDATED', 'Product Updated'), ('PRODUCT_DELETED', 'Product Deleted'), ('CATEGORY_CREATED', 'Category Created'), ('CATEGORY_UPDATED', 'Category Updated'), ('CATEGORY_DELETED', 'Category Deleted')], max_length=50),
        ),
    ]
