# Generated by Django 5.1.2 on 2025-01-09 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_alter_useraction_action_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='updated_by',
        ),
    ]
