# Generated by Django 5.1.2 on 2025-01-22 05:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_product_in_sale_product_updated_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='in_sale',
            field=models.BooleanField(default=False),
        ),
    ]
