# Generated by Django 5.1.2 on 2025-01-22 05:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_alter_product_in_sale'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.CreateModel(
            name='Navbar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField()),
                ('status', models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_navbars', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_navbars', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Navbar',
            },
        ),
    ]
