# Generated by Django 5.1.2 on 2025-01-22 09:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_alter_category_status_alter_vendor_status_navbar'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='updated_by',
        ),
        migrations.AddField(
            model_name='navbar',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='navbar',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='core.navbar'),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_navbars', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
