# Generated by Django 5.1.2 on 2025-01-22 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_navbar_sub_nav'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='sub_nav',
            field=models.CharField(max_length=100),
        ),
    ]
