# Generated by Django 5.1.2 on 2025-01-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_alter_navbar_sub_nav'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='sub_nav',
        ),
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
