# Generated by Django 5.1.2 on 2025-01-22 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_remove_navbar_sub_nav_alter_navbar_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.URLField(blank=True, default='#', null=True),
        ),
    ]
