# Generated by Django 5.1.2 on 2025-01-22 10:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_alter_navbar_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='url',
            field=models.URLField(blank=True, default='http://127.0.0.1:8000/#', null=True),
        ),
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='advertisements/')),
                ('is_active', models.BooleanField(default=True)),
                ('timer', models.IntegerField(default=5)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_advertisements', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
