# Generated by Django 5.1.2 on 2025-01-22 11:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_alter_navbar_url_advertisement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='advertisement',
            name='image',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='title',
            field=models.CharField(default='Default Advertisement Title', max_length=100),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timer',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='category',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='AdvertisementImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='advertisements/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('advertisement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='core.advertisement')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
