# Generated by Django 5.1.2 on 2025-01-23 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_remove_advertisement_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='timer',
            field=models.IntegerField(default=5),
        ),
    ]
