# Generated by Django 5.1.2 on 2025-01-23 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_alter_advertisement_timer'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('is_Active', 'Active'), ('is_Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
