# Generated by Django 5.1.2 on 2025-01-23 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_advertisement_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='status',
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='timer',
            field=models.PositiveIntegerField(default=5),
        ),
    ]
