# Generated by Django 5.1.2 on 2025-01-23 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_remove_advertisement_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='advertisement',
            name='is_active',
        ),
        migrations.AddField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
    ]
