# Generated by Django 5.1.2 on 2025-01-29 06:47

import shortuuid.django_fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_remove_advertisement_is_active_advertisement_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='aid',
            field=shortuuid.django_fields.ShortUUIDField(alphabet='abcdegh12345', length=10, max_length=20, prefix='adv', unique=True),
        ),
    ]
