# Generated by Django 5.1.2 on 2025-01-29 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_remove_advertisementimage_advertisement_ad_adimage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ad',
            name='image',
            field=models.ImageField(upload_to='Ad'),
        ),
    ]
