# Generated by Django 5.1.2 on 2025-01-29 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_alter_adimage_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='adimage',
            old_name='Ad',
            new_name='ad',
        ),
    ]
