# Generated by Django 5.1.2 on 2025-02-28 06:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_slider'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True, default='http://127.0.0.1:8000/#', null=True)),
                ('status', models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('order', models.IntegerField(default=0)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_footers', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.footer')),
            ],
            options={
                'verbose_name_plural': 'Footers',
            },
        ),
    ]
