# Generated by Django 5.1.2 on 2025-02-28 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_footer'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='footer',
            options={},
        ),
        migrations.RemoveField(
            model_name='footer',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='order',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='title',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='url',
        ),
        migrations.AddField(
            model_name='footer',
            name='address',
            field=models.CharField(default='Kathmandu, Nepal', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='content_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='cookies_setting',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='cookies_setting_url',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='description',
            field=models.CharField(default='This is the footer description', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='email',
            field=models.EmailField(blank=True, default='pd@gmail.com', max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='impo_link_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='link1',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='link2',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='link3',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='link4',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='map_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='map_url',
            field=models.URLField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='footer',
            name='phone_number',
            field=models.CharField(blank=True, default='9841234567', max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_policy',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='privacy_policy_url',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_icon1',
            field=models.ImageField(blank=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_icon2',
            field=models.ImageField(blank=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_icon3',
            field=models.ImageField(blank=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_icon4',
            field=models.ImageField(blank=True, upload_to='social_icons/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_link1',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_link2',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_link3',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_link4',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
        migrations.AddField(
            model_name='footer',
            name='social_status',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='tele_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='footer',
            name='terms_of_services',
            field=models.CharField(default='Terms of Services', max_length=255),
        ),
        migrations.AddField(
            model_name='footer',
            name='terms_of_services_url',
            field=models.URLField(default='https://www.w3schools.com/ai/ai_chartjs.asp'),
        ),
    ]
