# Generated by Django 5.1.2 on 2025-02-28 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_footer_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footer',
            name='address',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='cookies_setting',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='cookies_setting_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='description',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='email',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='impo_link_status',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='link4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='map_status',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='map_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='privacy_policy',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='privacy_policy_url',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_icon1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_icon2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_icon3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_icon4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_link1',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_link2',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_link3',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_link4',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='social_status',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='status',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='tele_number',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='terms_of_services',
        ),
        migrations.RemoveField(
            model_name='footer',
            name='terms_of_services_url',
        ),
        migrations.AddField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer/logo/'),
        ),
        migrations.AddField(
            model_name='footer',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='FooterSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('order', models.IntegerField(default=0)),
                ('footer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='core.footer')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('url', models.URLField()),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='core.footersection')),
            ],
        ),
    ]
