# Generated by Django 5.1.2 on 2025-02-28 09:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0074_remove_footer_address_remove_footer_cookies_setting_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='footersection',
            name='footer',
        ),
        migrations.AddField(
            model_name='footer',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_footers', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='footer',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='core.footer'),
        ),
        migrations.AddField(
            model_name='footer',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='footer',
            name='title',
            field=models.CharField(default='Study in India', max_length=100),
        ),
        migrations.AddField(
            model_name='footer',
            name='url',
            field=models.URLField(blank=True, default='https://studyinindia.com.np/', null=True),
        ),
        migrations.AlterField(
            model_name='footer',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='footer'),
        ),
        migrations.DeleteModel(
            name='FooterLink',
        ),
        migrations.DeleteModel(
            name='FooterSection',
        ),
    ]
