# Generated by Django 5.1.2 on 2025-03-01 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075_remove_footersection_footer_footer_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='footer',
            name='title',
            field=models.CharField(blank=True, default='Study in India', max_length=100, null=True),
        ),
    ]
