# Generated by Django 5.1.2 on 2025-03-01 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_alter_footer_title'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='logo')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('outofstock', 'Out of Stock'), ('Pending', 'Pending'), ('Discontinued', 'Discontinued'), ('Inactive', 'Inactive')], default='Active', max_length=20)),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='updated_logos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Logos',
            },
        ),
    ]
