# Generated by Django 5.1.2 on 2025-03-25 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_about_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='size',
            field=models.CharField(default='Medium', max_length=50),
        ),
    ]
