# Generated by Django 5.1.2 on 2025-03-25 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0080_alter_product_color_alter_product_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='color',
            field=models.CharField(help_text='Comma-separated color hex values', max_length=255),
        ),
    ]
