# Generated by Django 5.1.2 on 2025-03-25 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_alter_ad_status_alter_category_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartorder',
            name='color',
            field=models.ManyToManyField(to='core.color'),
        ),
        migrations.AddField(
            model_name='cartorder',
            name='size',
            field=models.ManyToManyField(to='core.size'),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='color',
            field=models.ManyToManyField(to='core.color'),
        ),
        migrations.AddField(
            model_name='cartorderitems',
            name='size',
            field=models.ManyToManyField(to='core.size'),
        ),
    ]
