# Generated by Django 5.1.2 on 2024-10-24 05:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0003_user_profile_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='profile_pic',
        ),
    ]
