# Generated by Django 5.1.2 on 2024-10-24 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0005_user_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
    ]
