# Generated by Django 5.1.2 on 2024-10-24 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0006_remove_user_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
